### ISSUE TITLE
Ajustar legenda do gráfico 4

### ISSUE THREAD

**Issue by chaydson** [chaydson/GCES_MEPA_ISSUES-2024.2#83]
No relatório detalhado, quando o contrato proposto é verde, o gráfico mostrado é esse:

![image](/uploads/3cc5d54bfaf2998e3fa8b99795f4f0ea/image.png){width=741 height=415}

Aparecem legendas para "Demanda proposta ponta" e "Demanda proposta fora ponta".

Deve aparecer apenas "Demanda proposta" com um valor único.

**Comment by chaydson** [comment]
https://gitlab.com/lappis-unb/projetos-energia/mec-energia/mec-energia-web/-/issues/439

**Comment by Mateuszinnn** [comment]
Feito
